name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@master
      name: Cargo build
      with:
        args: cargo build --verbose
    - uses: icepuma/rust-action@master
      name: Cargo test
      with:
        args: cargo test --verbose
    - uses: icepuma/rust-action@master
      name: Rustfmt
      with:
        args: cargo fmt -- --check
    - uses: icepuma/rust-action@master
      name: Clippy
      with:
        args: cargo clippy -- -Dwarnings
